# blocklist
branches:
  only: master
dist: xenial
language: python
cache: pip
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- make
# deploy:
#   provider: releases
#   api_key: $TOKEN
#   file: assignment2/2_RegularizationTut_STUDENT.ipynb
#   skip_cleanup: true
#   draft: true
#   on:
#       branch: test/jupytext
# after_success:
#   - git config --global user.email ${EMAIL}
#   - git config --global user.name ${USER}
#   - git checkout build
#   - git add *.ipynb
#   - "git commit --message \"[skip travis] Travis build: ${TRAVIS_BUILD_NUMBER}\""
#   - git remote add origin-pages https://${TOKEN}@github.com/sirexeclp/ml-in-prec-med.git > /dev/null 2>&1
#   - git push --quiet --set-upstream origin-pages build

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master